name: cloud_flutter
description: A new Flutter module.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^0.4.2
  http: '>=0.11.3+12'
  font_awesome_flutter: ^8.2.0
  dio: ^3.0.4
  fluttertoast: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.cloud_flutter
    iosBundleIdentifier: com.example.cloudFlutter
